### ISSUE TITLE
webpack.mix.js is not compatible with new Nova 4 structure

### ISSUE THREAD

**Issue by Kreshnik** [wearedevtical/nova-qrcode-field#11]
## Nova Verison
4.4.2

## Error
runtime-core.esm-bundler.js:226 TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (qrcode:1:39163)

## Assumption 
According to the [upgrade guide](https://nova.laravel.com/docs/4.0/upgrade.html) the following changes must be applied on the `webpack.mix.js` file.

```
// Before...
mix.js('resources/js/field.js', 'js') 

// After...
require('./nova.mix')

mix.js('resources/js/field.js', 'js').vue({ version: 3 })
  .nova('vendor/package')
  ```

**Comment by Kristories** [comment]
Fix #12
